export const cartType = {
    TOGGLE_CART: "TOGGLE_CART",
    CART_SUCCESS: "CART_SUCCESS",
    CART_FAIL: "CART_FAIL",
    CART_START: "CART_START",
    CART_CLEAR: "CART_CLEAR",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
}